version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: formation-iris-fhir
    hostname: formation-iris-fhir
    restart: always
    ports: 
      - 10000:1972
      - 10001:52773
      - 10002:53773
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    volumes:
      - ./data:/data
